var geojson_TrainStationExits = {
"type": "FeatureCollection",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
                                                                                
"features": [
{ "type": "Feature", "properties": { "STATION_NA": "TANAH MERAH MRT STATION", "EXIT_CODE": "B" }, "geometry": { "type": "Point", "coordinates": [ 103.945723, 1.327061 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "TANAH MERAH MRT STATION", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.945794, 1.326857 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "CLEMENTI MRT STATION", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.764982, 1.315373 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "CLEMENTI MRT STATION", "EXIT_CODE": "B" }, "geometry": { "type": "Point", "coordinates": [ 103.765185, 1.315469 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "BUONA VISTA MRT STATION", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.790449, 1.307309 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "BUONA VISTA MRT STATION", "EXIT_CODE": "B" }, "geometry": { "type": "Point", "coordinates": [ 103.790656, 1.307197 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "BUONA VISTA MRT STATION", "EXIT_CODE": "C" }, "geometry": { "type": "Point", "coordinates": [ 103.790599, 1.306912 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "QUEENSTOWN MRT STATION", "EXIT_CODE": "B" }, "geometry": { "type": "Point", "coordinates": [ 103.806311, 1.294329 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "QUEENSTOWN MRT STATION", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.806182, 1.294247 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "REDHILL MRT STATION", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.816994, 1.289370 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "REDHILL MRT STATION", "EXIT_CODE": "B" }, "geometry": { "type": "Point", "coordinates": [ 103.817249, 1.289485 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "COMMONWEALTH MRT STATION", "EXIT_CODE": "B" }, "geometry": { "type": "Point", "coordinates": [ 103.798057, 1.302752 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "COMMONWEALTH MRT STATION", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.797958, 1.302648 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "TIONG BAHRU MRT STATION", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.826990, 1.285759 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "TIONG BAHRU MRT STATION", "EXIT_CODE": "B" }, "geometry": { "type": "Point", "coordinates": [ 103.827496, 1.286361 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "HARBOURFRONT MRT STATION", "EXIT_CODE": "C" }, "geometry": { "type": "Point", "coordinates": [ 103.822531, 1.265259 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "HARBOURFRONT MRT STATION", "EXIT_CODE": "B" }, "geometry": { "type": "Point", "coordinates": [ 103.820508, 1.265154 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "ORCHARD MRT STATION", "EXIT_CODE": "E" }, "geometry": { "type": "Point", "coordinates": [ 103.832039, 1.304560 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "ORCHARD MRT STATION", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.832524, 1.304892 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "NEWTON MRT STATION", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.837881, 1.312597 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "NEWTON MRT STATION", "EXIT_CODE": "B" }, "geometry": { "type": "Point", "coordinates": [ 103.838219, 1.312075 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "ORCHARD MRT STATION", "EXIT_CODE": "C" }, "geometry": { "type": "Point", "coordinates": [ 103.832619, 1.304354 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "LAVENDER MRT STATION", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.863043, 1.307169 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "LAVENDER MRT STATION", "EXIT_CODE": "B" }, "geometry": { "type": "Point", "coordinates": [ 103.862650, 1.307618 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "KALLANG MRT STATION", "EXIT_CODE": "B" }, "geometry": { "type": "Point", "coordinates": [ 103.871587, 1.311781 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "KALLANG MRT STATION", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.871730, 1.311540 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "ALJUNIED MRT STATION", "EXIT_CODE": "B" }, "geometry": { "type": "Point", "coordinates": [ 103.882472, 1.316487 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "ALJUNIED MRT STATION", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.882496, 1.316238 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "LITTLE INDIA MRT STATION", "EXIT_CODE": "B" }, "geometry": { "type": "Point", "coordinates": [ 103.848985, 1.306563 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "FARRER PARK MRT STATION", "EXIT_CODE": "B" }, "geometry": { "type": "Point", "coordinates": [ 103.854763, 1.313543 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "FARRER PARK MRT STATION", "EXIT_CODE": "E" }, "geometry": { "type": "Point", "coordinates": [ 103.852650, 1.311883 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "FARRER PARK MRT STATION", "EXIT_CODE": "F" }, "geometry": { "type": "Point", "coordinates": [ 103.853199, 1.311422 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "PROMENADE MRT STATION", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.860673, 1.291711 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "TOA PAYOH MRT STATION", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.847723, 1.332376 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "LAKESIDE MRT STATION", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.720448, 1.343983 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "CHINESE GARDEN MRT STATION", "EXIT_CODE": "C" }, "geometry": { "type": "Point", "coordinates": [ 103.733393, 1.341565 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "CHINESE GARDEN MRT STATION", "EXIT_CODE": "B" }, "geometry": { "type": "Point", "coordinates": [ 103.732741, 1.341982 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "CHINESE GARDEN MRT STATION", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.732220, 1.342438 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "JURONG EAST MRT STATION", "EXIT_CODE": "C" }, "geometry": { "type": "Point", "coordinates": [ 103.742762, 1.332748 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "JURONG EAST MRT STATION", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.741759, 1.333989 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "JURONG EAST MRT STATION", "EXIT_CODE": "B" }, "geometry": { "type": "Point", "coordinates": [ 103.742640, 1.332526 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "YEW TEE MRT STATION", "EXIT_CODE": "B" }, "geometry": { "type": "Point", "coordinates": [ 103.747329, 1.398067 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "YEW TEE MRT STATION", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.747195, 1.397655 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "YEW TEE MRT STATION", "EXIT_CODE": "C" }, "geometry": { "type": "Point", "coordinates": [ 103.747431, 1.397000 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "YEW TEE MRT STATION", "EXIT_CODE": "D" }, "geometry": { "type": "Point", "coordinates": [ 103.747111, 1.397272 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "BUKIT GOMBAK MRT STATION", "EXIT_CODE": "B" }, "geometry": { "type": "Point", "coordinates": [ 103.752092, 1.358695 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "CHOA CHU KANG MRT STATION", "EXIT_CODE": "C" }, "geometry": { "type": "Point", "coordinates": [ 103.744517, 1.385736 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "CHOA CHU KANG MRT STATION", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.744557, 1.385431 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "ORCHARD MRT STATION", "EXIT_CODE": "D" }, "geometry": { "type": "Point", "coordinates": [ 103.832770, 1.304161 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "ORCHARD MRT STATION", "EXIT_CODE": "B" }, "geometry": { "type": "Point", "coordinates": [ 103.832171, 1.303167 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "SOMERSET MRT STATION", "EXIT_CODE": "B" }, "geometry": { "type": "Point", "coordinates": [ 103.838458, 1.300766 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "DHOBY GHAUT MRT STATION", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.846787, 1.298445 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "DHOBY GHAUT MRT STATION", "EXIT_CODE": "B" }, "geometry": { "type": "Point", "coordinates": [ 103.845229, 1.299055 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "DHOBY GHAUT MRT STATION", "EXIT_CODE": "E" }, "geometry": { "type": "Point", "coordinates": [ 103.845372, 1.299748 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "DHOBY GHAUT MRT STATION", "EXIT_CODE": "F" }, "geometry": { "type": "Point", "coordinates": [ 103.845842, 1.299634 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "BUGIS MRT STATION", "EXIT_CODE": "C" }, "geometry": { "type": "Point", "coordinates": [ 103.855685, 1.300006 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "CITY HALL MRT STATION", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.853020, 1.293227 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "CITY HALL MRT STATION", "EXIT_CODE": "B" }, "geometry": { "type": "Point", "coordinates": [ 103.851960, 1.293099 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "BUGIS MRT STATION", "EXIT_CODE": "B" }, "geometry": { "type": "Point", "coordinates": [ 103.856336, 1.300782 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "BUGIS MRT STATION", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.855924, 1.301204 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "OUTRAM PARK MRT STATION", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.838657, 1.281602 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "OUTRAM PARK MRT STATION", "EXIT_CODE": "B" }, "geometry": { "type": "Point", "coordinates": [ 103.838934, 1.281675 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "TANJONG PAGAR MRT STATION", "EXIT_CODE": "B" }, "geometry": { "type": "Point", "coordinates": [ 103.846544, 1.276671 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "TANJONG PAGAR MRT STATION", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.844834, 1.276408 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "TANJONG PAGAR MRT STATION", "EXIT_CODE": "C" }, "geometry": { "type": "Point", "coordinates": [ 103.846533, 1.276089 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "TANJONG PAGAR MRT STATION", "EXIT_CODE": "D" }, "geometry": { "type": "Point", "coordinates": [ 103.846908, 1.276064 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "MARINA BAY MRT STATION", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.854948, 1.275708 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "RAFFLES PLACE MRT STATION", "EXIT_CODE": "H" }, "geometry": { "type": "Point", "coordinates": [ 103.851621, 1.285258 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "RAFFLES PLACE MRT STATION", "EXIT_CODE": "E" }, "geometry": { "type": "Point", "coordinates": [ 103.851522, 1.283211 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "RAFFLES PLACE MRT STATION", "EXIT_CODE": "B" }, "geometry": { "type": "Point", "coordinates": [ 103.851479, 1.284606 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "RAFFLES PLACE MRT STATION", "EXIT_CODE": "G" }, "geometry": { "type": "Point", "coordinates": [ 103.851478, 1.285016 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "RAFFLES PLACE MRT STATION", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.851438, 1.284125 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "RAFFLES PLACE MRT STATION", "EXIT_CODE": "D" }, "geometry": { "type": "Point", "coordinates": [ 103.851353, 1.283641 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "DHOBY GHAUT MRT STATION", "EXIT_CODE": "D" }, "geometry": { "type": "Point", "coordinates": [ 103.845030, 1.299930 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "OUTRAM PARK MRT STATION", "EXIT_CODE": "H" }, "geometry": { "type": "Point", "coordinates": [ 103.840386, 1.280213 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "OUTRAM PARK MRT STATION", "EXIT_CODE": "G" }, "geometry": { "type": "Point", "coordinates": [ 103.839549, 1.278946 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "OUTRAM PARK MRT STATION", "EXIT_CODE": "F" }, "geometry": { "type": "Point", "coordinates": [ 103.838537, 1.279051 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "CLARK QUAY MRT STATION", "EXIT_CODE": "C" }, "geometry": { "type": "Point", "coordinates": [ 103.846665, 1.289383 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "CLARKE QUAY MRT STATION", "EXIT_CODE": "F" }, "geometry": { "type": "Point", "coordinates": [ 103.847129, 1.289405 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "CLARKE QUAY MRT STATION", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.846064, 1.286898 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "CLARK QUAY MRT STATION", "EXIT_CODE": "E" }, "geometry": { "type": "Point", "coordinates": [ 103.847032, 1.289000 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "CHINATOWN MRT STATION", "EXIT_CODE": "C" }, "geometry": { "type": "Point", "coordinates": [ 103.842812, 1.284674 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "CHOA CHU KANG MRT STATION", "EXIT_CODE": "B" }, "geometry": { "type": "Point", "coordinates": [ 103.744595, 1.384979 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "CHINATOWN MRT STATION", "EXIT_CODE": "E" }, "geometry": { "type": "Point", "coordinates": [ 103.844428, 1.285044 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "BUKIT BATOK MRT STATION", "EXIT_CODE": "C" }, "geometry": { "type": "Point", "coordinates": [ 103.749766, 1.349520 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "CHINATOWN MRT STATION", "EXIT_CODE": "D" }, "geometry": { "type": "Point", "coordinates": [ 103.843476, 1.285406 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "BUKIT BATOK MRT STATION", "EXIT_CODE": "D" }, "geometry": { "type": "Point", "coordinates": [ 103.749118, 1.348405 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "BUKIT BATOK MRT STATION", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.749973, 1.349561 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "BUKIT GOMBAK MRT STATION", "EXIT_CODE": "C" }, "geometry": { "type": "Point", "coordinates": [ 103.751726, 1.359064 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "BUKIT GOMBAK MRT STATION", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.752076, 1.359069 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "BUKIT GOMBAK MRT STATION", "EXIT_CODE": "D" }, "geometry": { "type": "Point", "coordinates": [ 103.751950, 1.359297 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "BOON LAY MRT STATION", "EXIT_CODE": "B" }, "geometry": { "type": "Point", "coordinates": [ 103.706145, 1.338420 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "BOON LAY MRT STATION", "EXIT_CODE": "C" }, "geometry": { "type": "Point", "coordinates": [ 103.705955, 1.338738 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "BOON LAY MRT STATION", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.705408, 1.338279 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "LAKESIDE MRT STATION", "EXIT_CODE": "C" }, "geometry": { "type": "Point", "coordinates": [ 103.721712, 1.344304 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "LAKESIDE MRT STATION", "EXIT_CODE": "B" }, "geometry": { "type": "Point", "coordinates": [ 103.721075, 1.344081 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "KRANJI MRT STATION", "EXIT_CODE": "C" }, "geometry": { "type": "Point", "coordinates": [ 103.761754, 1.425125 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "KRANJI MRT STATION", "EXIT_CODE": "B" }, "geometry": { "type": "Point", "coordinates": [ 103.761940, 1.424852 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "KRANJI MRT STATION", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.762018, 1.424739 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "MARSILING MRT STATION", "EXIT_CODE": "C" }, "geometry": { "type": "Point", "coordinates": [ 103.773820, 1.432469 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "MARSILING MRT STATION", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.774210, 1.432801 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "PAYA LEBAR MRT STATION", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.892788, 1.318215 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "PAYA LEBAR MRT STATION", "EXIT_CODE": "B" }, "geometry": { "type": "Point", "coordinates": [ 103.892217, 1.318347 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "YIO CHU KANG MRT STATION", "EXIT_CODE": "C" }, "geometry": { "type": "Point", "coordinates": [ 103.844645, 1.381953 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "YIO CHU KANG MRT STATION", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.844834, 1.381644 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "YIO CHU KANG MRT STATION", "EXIT_CODE": "B" }, "geometry": { "type": "Point", "coordinates": [ 103.844946, 1.381547 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "WOODLANDS MRT STATION", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.786393, 1.436752 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "WOODLANDS MRT STATION", "EXIT_CODE": "C" }, "geometry": { "type": "Point", "coordinates": [ 103.787224, 1.437094 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "WOODLANDS MRT STATION", "EXIT_CODE": "B" }, "geometry": { "type": "Point", "coordinates": [ 103.785844, 1.436596 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "ADMIRALTY MRT STATION", "EXIT_CODE": "C" }, "geometry": { "type": "Point", "coordinates": [ 103.800542, 1.440596 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "ADMIRALTY MRT STATION", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.800989, 1.440345 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "SEMBAWANG MRT STATION", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.820109, 1.448837 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "SEMBAWANG MRT STATION", "EXIT_CODE": "B" }, "geometry": { "type": "Point", "coordinates": [ 103.819790, 1.448768 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "YISHUN MRT STATION", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.834783, 1.429397 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "YISHUN MRT STATION", "EXIT_CODE": "D" }, "geometry": { "type": "Point", "coordinates": [ 103.834863, 1.429106 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "KHATIB MRT STATION", "EXIT_CODE": "C" }, "geometry": { "type": "Point", "coordinates": [ 103.832886, 1.417544 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "KHATIB MRT STATION", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.832922, 1.417058 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "KHATIB MRT STATION", "EXIT_CODE": "B" }, "geometry": { "type": "Point", "coordinates": [ 103.832706, 1.417143 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "SEMBAWANG MRT STATION", "EXIT_CODE": "D" }, "geometry": { "type": "Point", "coordinates": [ 103.820401, 1.448927 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "PASIR RIS MRT STATION", "EXIT_CODE": "B" }, "geometry": { "type": "Point", "coordinates": [ 103.949136, 1.372886 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "PASIR RIS MRT STATION", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.949333, 1.372841 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "TAMPINES MRT STATION", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.944766, 1.353764 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "TAMPINES MRT STATION", "EXIT_CODE": "C" }, "geometry": { "type": "Point", "coordinates": [ 103.944903, 1.353398 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "TAMPINES MRT STATION", "EXIT_CODE": "B" }, "geometry": { "type": "Point", "coordinates": [ 103.945089, 1.353539 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "HOUGANG MRT STATION", "EXIT_CODE": "C" }, "geometry": { "type": "Point", "coordinates": [ 103.891975, 1.372141 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "HOUGANG MRT STATION", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.892445, 1.370208 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "KOVAN MRT STATION", "EXIT_CODE": "B" }, "geometry": { "type": "Point", "coordinates": [ 103.884721, 1.360205 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "KOVAN MRT STATION", "EXIT_CODE": "C" }, "geometry": { "type": "Point", "coordinates": [ 103.885450, 1.360028 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "KOVAN MRT STATION", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.884307, 1.359707 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "EUNOS MRT STATION", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.902894, 1.319517 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "EUNOS MRT STATION", "EXIT_CODE": "B" }, "geometry": { "type": "Point", "coordinates": [ 103.902582, 1.319562 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "KEMBANGAN MRT STATION", "EXIT_CODE": "B" }, "geometry": { "type": "Point", "coordinates": [ 103.912899, 1.321152 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "KEMBANGAN MRT STATION", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.912941, 1.320923 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "BEDOK MRT STATION", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.929157, 1.323568 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "BEDOK MRT STATION", "EXIT_CODE": "B" }, "geometry": { "type": "Point", "coordinates": [ 103.929673, 1.324268 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "ANG MO KIO MRT STATION", "EXIT_CODE": "B" }, "geometry": { "type": "Point", "coordinates": [ 103.849596, 1.369685 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "ANG MO KIO MRT STATION", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.849939, 1.369464 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "BISHAN MRT STATION", "EXIT_CODE": "B" }, "geometry": { "type": "Point", "coordinates": [ 103.848312, 1.351064 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "BISHAN MRT STATION", "EXIT_CODE": "E" }, "geometry": { "type": "Point", "coordinates": [ 103.848432, 1.351034 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "BISHAN MRT STATION", "EXIT_CODE": "C" }, "geometry": { "type": "Point", "coordinates": [ 103.848209, 1.350584 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "BRADDELL MRT STATION", "EXIT_CODE": "C" }, "geometry": { "type": "Point", "coordinates": [ 103.847440, 1.340672 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "BRADDELL MRT STATION", "EXIT_CODE": "B" }, "geometry": { "type": "Point", "coordinates": [ 103.846406, 1.340744 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "BRADDELL MRT STATION", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.846429, 1.341068 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "TOA PAYOH MRT STATION", "EXIT_CODE": "B" }, "geometry": { "type": "Point", "coordinates": [ 103.847577, 1.332315 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "TOA PAYOH MRT STATION", "EXIT_CODE": "C" }, "geometry": { "type": "Point", "coordinates": [ 103.847319, 1.332994 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "NOVENA MRT STATION", "EXIT_CODE": "B" }, "geometry": { "type": "Point", "coordinates": [ 103.843339, 1.319895 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "NOVENA MRT STATION", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.844389, 1.321094 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "TOA PAYOH MRT STATION", "EXIT_CODE": "D" }, "geometry": { "type": "Point", "coordinates": [ 103.846517, 1.333278 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "WOODLEIGH MRT STATION", "EXIT_CODE": "C" }, "geometry": { "type": "Point", "coordinates": [ 103.871053, 1.339867 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "WOODLEIGH MRT STATION", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.870940, 1.338510 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "WOODLEIGH MRT STATION", "EXIT_CODE": "B" }, "geometry": { "type": "Point", "coordinates": [ 103.870508, 1.338583 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "BOON KENG MRT STATION", "EXIT_CODE": "B" }, "geometry": { "type": "Point", "coordinates": [ 103.861903, 1.319235 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "POTONG PASIR MRT STATION", "EXIT_CODE": "C" }, "geometry": { "type": "Point", "coordinates": [ 103.868703, 1.331066 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "POTONG PASIR MRT STATION", "EXIT_CODE": "B" }, "geometry": { "type": "Point", "coordinates": [ 103.869333, 1.331148 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "SOMERSET MRT STATION", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.838399, 1.300028 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "ONE-NORTH MRT STATION", "EXIT_CODE": "C" }, "geometry": { "type": "Point", "coordinates": [ 103.787565, 1.299714 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "BRAS BASAH MRT STATION", "EXIT_CODE": "B" }, "geometry": { "type": "Point", "coordinates": [ 103.850474, 1.296046 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "BRAS BASAH MRT STATION", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.851327, 1.296858 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "BRAS BASAH MRT STATION", "EXIT_CODE": "C" }, "geometry": { "type": "Point", "coordinates": [ 103.850249, 1.297014 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "BRAS BASAH MRT STATION", "EXIT_CODE": "D" }, "geometry": { "type": "Point", "coordinates": [ 103.850157, 1.297551 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "BRAS BASAH MRT STATION", "EXIT_CODE": "E" }, "geometry": { "type": "Point", "coordinates": [ 103.850423, 1.297535 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "ESPLANADE MRT STATION", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.856305, 1.293370 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "ESPLANADE MRT STATION", "EXIT_CODE": "E" }, "geometry": { "type": "Point", "coordinates": [ 103.855567, 1.293128 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "ESPLANADE MRT STATION", "EXIT_CODE": "F" }, "geometry": { "type": "Point", "coordinates": [ 103.855104, 1.293819 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "ESPLANADE MRT STATION", "EXIT_CODE": "D" }, "geometry": { "type": "Point", "coordinates": [ 103.855833, 1.292623 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "PROMENADE MRT STATION", "EXIT_CODE": "B" }, "geometry": { "type": "Point", "coordinates": [ 103.860136, 1.293862 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "NICOLL HIGHWAY MRT STATION", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.863505, 1.300169 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "STADIUM MRT STATION", "EXIT_CODE": "B" }, "geometry": { "type": "Point", "coordinates": [ 103.876226, 1.303370 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "STADIUM MRT STATION", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.874399, 1.302511 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "MOUNTBATTEN MRT STATION", "EXIT_CODE": "B" }, "geometry": { "type": "Point", "coordinates": [ 103.883248, 1.306045 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "MOUNTBATTEN MRT STATION", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.882597, 1.306752 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "DAKOTA MRT STATION", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.889307, 1.308814 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "DAKOTA MRT STATION", "EXIT_CODE": "B" }, "geometry": { "type": "Point", "coordinates": [ 103.887979, 1.308096 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "PAYA LEBAR MRT STATION", "EXIT_CODE": "C" }, "geometry": { "type": "Point", "coordinates": [ 103.891721, 1.318149 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "PAYA LEBAR MRT STATION", "EXIT_CODE": "D" }, "geometry": { "type": "Point", "coordinates": [ 103.892077, 1.316587 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "MACPHERSON MRT STATION", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.889793, 1.326678 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "MACPHERSON MRT STATION", "EXIT_CODE": "B" }, "geometry": { "type": "Point", "coordinates": [ 103.890665, 1.325855 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "MACPHERSON MRT STATION", "EXIT_CODE": "C" }, "geometry": { "type": "Point", "coordinates": [ 103.890262, 1.325481 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "TAI SENG MRT STATION", "EXIT_CODE": "B" }, "geometry": { "type": "Point", "coordinates": [ 103.888214, 1.334620 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "BARTLEY MRT STATION", "EXIT_CODE": "B" }, "geometry": { "type": "Point", "coordinates": [ 103.878908, 1.343501 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "BARTLEY MRT STATION", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.880255, 1.342248 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "SERANGOON MRT STATION", "EXIT_CODE": "H" }, "geometry": { "type": "Point", "coordinates": [ 103.873546, 1.349727 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "SERANGOON MRT STATION", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.873957, 1.349481 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "SERANGOON MRT STATION", "EXIT_CODE": "D" }, "geometry": { "type": "Point", "coordinates": [ 103.874321, 1.349901 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "SERANGOON MRT STATION", "EXIT_CODE": "C" }, "geometry": { "type": "Point", "coordinates": [ 103.873694, 1.350595 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "SERANGOON MRT STATION", "EXIT_CODE": "F" }, "geometry": { "type": "Point", "coordinates": [ 103.871449, 1.350948 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "LORONG CHUAN MRT STATION", "EXIT_CODE": "B" }, "geometry": { "type": "Point", "coordinates": [ 103.862918, 1.351738 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "LORONG CHUAN MRT STATION", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.864933, 1.351439 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "MARYMOUNT MRT STATION", "EXIT_CODE": "B" }, "geometry": { "type": "Point", "coordinates": [ 103.840058, 1.347866 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "MARYMOUNT MRT STATION", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.839087, 1.348980 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "DHOBY GHAUT MRT STATION", "EXIT_CODE": "C" }, "geometry": { "type": "Point", "coordinates": [ 103.844747, 1.299649 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "CALDECOTT MRT STATION", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.839811, 1.337823 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "CALDECOTT MRT STATION", "EXIT_CODE": "B" }, "geometry": { "type": "Point", "coordinates": [ 103.839406, 1.337105 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "EXPO MRT STATION", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.961942, 1.335321 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "EXPO MRT STATION", "EXIT_CODE": "B" }, "geometry": { "type": "Point", "coordinates": [ 103.962075, 1.335252 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "ADMIRALTY MRT STATION", "EXIT_CODE": "B" }, "geometry": { "type": "Point", "coordinates": [ 103.800533, 1.440152 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "ADMIRALTY MRT STATION", "EXIT_CODE": "D" }, "geometry": { "type": "Point", "coordinates": [ 103.801364, 1.440533 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "ANG MO KIO MRT STATION", "EXIT_CODE": "C" }, "geometry": { "type": "Point", "coordinates": [ 103.849343, 1.369440 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "BAYFRONT MRT STATION", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.858731, 1.280967 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "BAYFRONT MRT STATION", "EXIT_CODE": "E" }, "geometry": { "type": "Point", "coordinates": [ 103.858441, 1.281104 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "BAYFRONT MRT STATION", "EXIT_CODE": "D" }, "geometry": { "type": "Point", "coordinates": [ 103.859493, 1.282834 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "BAYFRONT MRT STATION", "EXIT_CODE": "C" }, "geometry": { "type": "Point", "coordinates": [ 103.859596, 1.282834 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "BAYFRONT MRT STATION", "EXIT_CODE": "B" }, "geometry": { "type": "Point", "coordinates": [ 103.859759, 1.282705 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "BEAUTY WORLD MRT STATION", "EXIT_CODE": "B" }, "geometry": { "type": "Point", "coordinates": [ 103.775450, 1.341582 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "BISHAN MRT STATION", "EXIT_CODE": "D" }, "geometry": { "type": "Point", "coordinates": [ 103.850201, 1.351053 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "BISHAN MRT STATION", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.848304, 1.350579 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "BOON KENG MRT STATION", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.861502, 1.320106 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "SENGKANG MRT STATION", "EXIT_CODE": "D" }, "geometry": { "type": "Point", "coordinates": [ 103.895705, 1.392370 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "SENGKANG MRT STATION", "EXIT_CODE": "B" }, "geometry": { "type": "Point", "coordinates": [ 103.895636, 1.391795 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "SENGKANG MRT STATION", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.895405, 1.391829 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "SENGKANG MRT STATION", "EXIT_CODE": "C" }, "geometry": { "type": "Point", "coordinates": [ 103.895209, 1.390881 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "PUNGGOL MRT STATION", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.902305, 1.405339 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "PUNGGOL MRT STATION", "EXIT_CODE": "D" }, "geometry": { "type": "Point", "coordinates": [ 103.901798, 1.404438 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "PUNGGOL MRT STATION", "EXIT_CODE": "B" }, "geometry": { "type": "Point", "coordinates": [ 103.902598, 1.405186 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "PUNGGOL MRT STATION", "EXIT_CODE": "C" }, "geometry": { "type": "Point", "coordinates": [ 103.902115, 1.404300 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "BUANGKOK MRT STATION", "EXIT_CODE": "C" }, "geometry": { "type": "Point", "coordinates": [ 103.892883, 1.383409 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "BUANGKOK MRT STATION", "EXIT_CODE": "B" }, "geometry": { "type": "Point", "coordinates": [ 103.893463, 1.382649 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "YISHUN MRT STATION", "EXIT_CODE": "C" }, "geometry": { "type": "Point", "coordinates": [ 103.835090, 1.429116 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "YISHUN MRT STATION", "EXIT_CODE": "B" }, "geometry": { "type": "Point", "coordinates": [ 103.834865, 1.429636 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "YISHUN MRT STATION", "EXIT_CODE": "E" }, "geometry": { "type": "Point", "coordinates": [ 103.835643, 1.429665 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "SERANGOON MRT STATION", "EXIT_CODE": "G" }, "geometry": { "type": "Point", "coordinates": [ 103.872866, 1.350790 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "SERANGOON MRT STATION", "EXIT_CODE": "B" }, "geometry": { "type": "Point", "coordinates": [ 103.873641, 1.349833 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "SERANGOON MRT STATION", "EXIT_CODE": "E" }, "geometry": { "type": "Point", "coordinates": [ 103.872902, 1.350820 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "TAI SENG MRT STATION", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.887627, 1.335914 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "EUNOS MRT STATION", "EXIT_CODE": "C" }, "geometry": { "type": "Point", "coordinates": [ 103.903215, 1.319529 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "SEMBAWANG MRT STATION", "EXIT_CODE": "C" }, "geometry": { "type": "Point", "coordinates": [ 103.819758, 1.449156 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "HOUGANG MRT STATION", "EXIT_CODE": "B" }, "geometry": { "type": "Point", "coordinates": [ 103.892972, 1.371946 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "CHANGI AIRPORT MRT STATION", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.989276, 1.356341 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "CHANGI AIRPORT MRT STATION", "EXIT_CODE": "B" }, "geometry": { "type": "Point", "coordinates": [ 103.987304, 1.357220 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "ESPLANADE MRT STATION", "EXIT_CODE": "G" }, "geometry": { "type": "Point", "coordinates": [ 103.854920, 1.293586 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "ESPLANADE MRT STATION", "EXIT_CODE": "C" }, "geometry": { "type": "Point", "coordinates": [ 103.855855, 1.292904 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "ESPLANADE MRT STATION", "EXIT_CODE": "B" }, "geometry": { "type": "Point", "coordinates": [ 103.856175, 1.292927 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "RAFFLES PLACE MRT STATION", "EXIT_CODE": "C" }, "geometry": { "type": "Point", "coordinates": [ 103.851562, 1.283630 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "RAFFLES PLACE MRT STATION", "EXIT_CODE": "J" }, "geometry": { "type": "Point", "coordinates": [ 103.851296, 1.282626 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "RAFFLES PLACE MRT STATION", "EXIT_CODE": "F" }, "geometry": { "type": "Point", "coordinates": [ 103.850960, 1.282538 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "RAFFLES PLACE MRT STATION", "EXIT_CODE": "I" }, "geometry": { "type": "Point", "coordinates": [ 103.851433, 1.282382 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "TANJONG PAGAR MRT STATION", "EXIT_CODE": "E" }, "geometry": { "type": "Point", "coordinates": [ 103.847095, 1.276259 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "TANJONG PAGAR MRT STATION", "EXIT_CODE": "F" }, "geometry": { "type": "Point", "coordinates": [ 103.846927, 1.277379 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "TANJONG PAGAR MRT STATION", "EXIT_CODE": "G" }, "geometry": { "type": "Point", "coordinates": [ 103.846953, 1.277784 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "TANJONG PAGAR MRT STATION", "EXIT_CODE": "H" }, "geometry": { "type": "Point", "coordinates": [ 103.846445, 1.275450 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "OUTRAM PARK MRT STATION", "EXIT_CODE": "C" }, "geometry": { "type": "Point", "coordinates": [ 103.839374, 1.281150 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "OUTRAM PARK MRT STATION", "EXIT_CODE": "D" }, "geometry": { "type": "Point", "coordinates": [ 103.839417, 1.281357 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "OUTRAM PARK MRT STATION", "EXIT_CODE": "E" }, "geometry": { "type": "Point", "coordinates": [ 103.839789, 1.280993 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "DOVER MRT STATION", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.778304, 1.311415 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "DOVER MRT STATION", "EXIT_CODE": "B" }, "geometry": { "type": "Point", "coordinates": [ 103.778464, 1.311693 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "BOON LAY MRT STATION", "EXIT_CODE": "D" }, "geometry": { "type": "Point", "coordinates": [ 103.705650, 1.338629 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "BOON LAY MRT STATION", "EXIT_CODE": "E" }, "geometry": { "type": "Point", "coordinates": [ 103.705353, 1.338514 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "BOON LAY MRT STATION", "EXIT_CODE": "F" }, "geometry": { "type": "Point", "coordinates": [ 103.705795, 1.338273 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "BUKIT BATOK MRT STATION", "EXIT_CODE": "B" }, "geometry": { "type": "Point", "coordinates": [ 103.749936, 1.349389 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "JOO KOON MRT STATION", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.678520, 1.327502 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "JOO KOON MRT STATION", "EXIT_CODE": "B" }, "geometry": { "type": "Point", "coordinates": [ 103.678644, 1.327956 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "CHOA CHU KANG MRT STATION", "EXIT_CODE": "D" }, "geometry": { "type": "Point", "coordinates": [ 103.744223, 1.385705 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "KRANJI MRT STATION", "EXIT_CODE": "D" }, "geometry": { "type": "Point", "coordinates": [ 103.762496, 1.425124 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "MARSILING MRT STATION", "EXIT_CODE": "B" }, "geometry": { "type": "Point", "coordinates": [ 103.774410, 1.432751 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "MARSILING MRT STATION", "EXIT_CODE": "D" }, "geometry": { "type": "Point", "coordinates": [ 103.773997, 1.432751 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "HARBOURFRONT MRT STATION", "EXIT_CODE": "E" }, "geometry": { "type": "Point", "coordinates": [ 103.821580, 1.264971 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "HARBOURFRONT MRT STATION", "EXIT_CODE": "D" }, "geometry": { "type": "Point", "coordinates": [ 103.821398, 1.265979 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "HARBOURFRONT MRT STATION", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.820468, 1.266013 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "CHINATOWN MRT STATION", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.843797, 1.283712 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "CLARKE QUAY MRT STATION", "EXIT_CODE": "B" }, "geometry": { "type": "Point", "coordinates": [ 103.845903, 1.287805 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "CLARK QUAY MRT STATION", "EXIT_CODE": "G" }, "geometry": { "type": "Point", "coordinates": [ 103.846593, 1.289199 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "LITTLE INDIA MRT STATION", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.849360, 1.305605 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "LITTLE INDIA MRT STATION", "EXIT_CODE": "C" }, "geometry": { "type": "Point", "coordinates": [ 103.849704, 1.306351 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "LITTLE INDIA MRT STATION", "EXIT_CODE": "E" }, "geometry": { "type": "Point", "coordinates": [ 103.850322, 1.307426 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "FARRER PARK MRT STATION", "EXIT_CODE": "D" }, "geometry": { "type": "Point", "coordinates": [ 103.852974, 1.312453 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "FARRER PARK MRT STATION", "EXIT_CODE": "C" }, "geometry": { "type": "Point", "coordinates": [ 103.853266, 1.311910 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "FARRER PARK MRT STATION", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.854772, 1.312326 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "FARRER PARK MRT STATION", "EXIT_CODE": "G" }, "geometry": { "type": "Point", "coordinates": [ 103.855500, 1.312259 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "FARRER PARK MRT STATION", "EXIT_CODE": "I" }, "geometry": { "type": "Point", "coordinates": [ 103.855806, 1.311765 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "FARRER PARK MRT STATION", "EXIT_CODE": "H" }, "geometry": { "type": "Point", "coordinates": [ 103.856098, 1.311883 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "BOON KENG MRT STATION", "EXIT_CODE": "C" }, "geometry": { "type": "Point", "coordinates": [ 103.860706, 1.317914 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "POTONG PASIR MRT STATION", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.868966, 1.332801 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "NICOLL HIGHWAY MRT STATION", "EXIT_CODE": "B" }, "geometry": { "type": "Point", "coordinates": [ 103.864151, 1.299660 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "BOTANIC GARDENS MRT STATION", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.814976, 1.322534 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "FARRER ROAD MRT STATION", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.807965, 1.317493 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "FARRER ROAD MRT STATION", "EXIT_CODE": "B" }, "geometry": { "type": "Point", "coordinates": [ 103.807389, 1.317552 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "HOLLAND VILLAGE MRT STATION", "EXIT_CODE": "C" }, "geometry": { "type": "Point", "coordinates": [ 103.795753, 1.310711 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "HOLLAND VILLAGE MRT STATION", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.796139, 1.311220 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "HOLLAND VILLAGE MRT STATION", "EXIT_CODE": "B" }, "geometry": { "type": "Point", "coordinates": [ 103.795769, 1.311069 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "ONE-NORTH MRT STATION", "EXIT_CODE": "B" }, "geometry": { "type": "Point", "coordinates": [ 103.787927, 1.300359 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "ONE-NORTH MRT STATION", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.786907, 1.299027 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "KENT RIDGE MRT STATION", "EXIT_CODE": "B" }, "geometry": { "type": "Point", "coordinates": [ 103.784809, 1.292428 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "KENT RIDGE MRT STATION", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.784465, 1.294315 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "HAW PAR VILLA MRT STATION", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.782006, 1.283055 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "PASIR PANJANG MRT STATION", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.792030, 1.276003 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "LABRADOR PARK MRT STATION", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.802355, 1.272106 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "TELOK BLANGAH MRT STATION", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.809883, 1.270721 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "TAN KAH KEE MRT STATION", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.807799, 1.325333 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "CASHEW MRT STATION", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.764234, 1.369833 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "SIXTH AVENUE MRT STATION", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.796566, 1.330780 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "KING ALBERT PARK MRT STATION", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.783030, 1.335537 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "HILLVIEW MRT STATION", "EXIT_CODE": "B" }, "geometry": { "type": "Point", "coordinates": [ 103.767108, 1.362084 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "BUKIT PANJANG MRT STATION", "EXIT_CODE": "A1" }, "geometry": { "type": "Point", "coordinates": [ 103.761922, 1.379007 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "ROCHOR MRT STATION", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.852375, 1.303404 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "DOWNTOWN MRT STATION", "EXIT_CODE": "F" }, "geometry": { "type": "Point", "coordinates": [ 103.852427, 1.279796 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "TELOK AYER MRT STATION", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.848506, 1.281887 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "PIONEER MRT STATION", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.697155, 1.337344 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "PIONEER MRT STATION", "EXIT_CODE": "B" }, "geometry": { "type": "Point", "coordinates": [ 103.697129, 1.337831 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "TANJONG PAGAR MRT STATION", "EXIT_CODE": "I" }, "geometry": { "type": "Point", "coordinates": [ 103.845656, 1.276447 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "BUONA VISTA MRT STATION", "EXIT_CODE": "D" }, "geometry": { "type": "Point", "coordinates": [ 103.790930, 1.306298 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "PROMENADE MRT STATION", "EXIT_CODE": "C" }, "geometry": { "type": "Point", "coordinates": [ 103.860236, 1.294102 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "MARINA BAY MRT STATION", "EXIT_CODE": "B" }, "geometry": { "type": "Point", "coordinates": [ 103.854312, 1.277456 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "KHATIB MRT STATION", "EXIT_CODE": "D" }, "geometry": { "type": "Point", "coordinates": [ 103.833231, 1.417869 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "SIMEI MRT STATION", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.953818, 1.342661 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "BEDOK MRT STATION", "EXIT_CODE": "C" }, "geometry": { "type": "Point", "coordinates": [ 103.929404, 1.324074 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "BUGIS MRT STATION", "EXIT_CODE": "D" }, "geometry": { "type": "Point", "coordinates": [ 103.856890, 1.299078 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "CITY HALL MRT STATION", "EXIT_CODE": "C" }, "geometry": { "type": "Point", "coordinates": [ 103.852980, 1.293041 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "QUEENSTOWN MRT STATION", "EXIT_CODE": "C" }, "geometry": { "type": "Point", "coordinates": [ 103.805584, 1.295446 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "QUEENSTOWN MRT STATION", "EXIT_CODE": "D" }, "geometry": { "type": "Point", "coordinates": [ 103.805492, 1.295382 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "COMMONWEALTH MRT STATION", "EXIT_CODE": "C" }, "geometry": { "type": "Point", "coordinates": [ 103.798778, 1.302077 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "COMMONWEALTH MRT STATION", "EXIT_CODE": "D" }, "geometry": { "type": "Point", "coordinates": [ 103.798720, 1.302012 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "CLEMENTI MRT STATION", "EXIT_CODE": "D" }, "geometry": { "type": "Point", "coordinates": [ 103.765570, 1.314078 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "CLEMENTI MRT STATION", "EXIT_CODE": "C" }, "geometry": { "type": "Point", "coordinates": [ 103.765749, 1.314162 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "JURONG EAST MRT STATION", "EXIT_CODE": "D" }, "geometry": { "type": "Point", "coordinates": [ 103.742298, 1.333581 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "ANG MO KIO MRT STATION", "EXIT_CODE": "D" }, "geometry": { "type": "Point", "coordinates": [ 103.849824, 1.369882 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "SOMERSET MRT STATION", "EXIT_CODE": "C" }, "geometry": { "type": "Point", "coordinates": [ 103.838765, 1.300436 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "SOMERSET MRT STATION", "EXIT_CODE": "D" }, "geometry": { "type": "Point", "coordinates": [ 103.839734, 1.300241 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "MARINA SOUTH PIER MRT STATION", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.862330, 1.270529 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "MARINA SOUTH PIER MRT STATION", "EXIT_CODE": "B" }, "geometry": { "type": "Point", "coordinates": [ 103.863579, 1.271437 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "CHINATOWN MRT STATION", "EXIT_CODE": "G" }, "geometry": { "type": "Point", "coordinates": [ 103.844458, 1.284736 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "CHINATOWN MRT STATION", "EXIT_CODE": "F" }, "geometry": { "type": "Point", "coordinates": [ 103.845462, 1.284274 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "BUKIT PANJANG MRT STATION", "EXIT_CODE": "B" }, "geometry": { "type": "Point", "coordinates": [ 103.761370, 1.378618 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "HILLVIEW MRT STATION", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.767688, 1.362474 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "BEAUTY WORLD MRT STATION", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.775984, 1.341696 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "BEAUTY WORLD MRT STATION", "EXIT_CODE": "C" }, "geometry": { "type": "Point", "coordinates": [ 103.775761, 1.339981 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "KING ALBERT PARK MRT STATION", "EXIT_CODE": "B" }, "geometry": { "type": "Point", "coordinates": [ 103.784561, 1.335976 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "SIXTH AVENUE MRT STATION", "EXIT_CODE": "B" }, "geometry": { "type": "Point", "coordinates": [ 103.796848, 1.331521 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "TAN KAH KEE MRT STATION", "EXIT_CODE": "B" }, "geometry": { "type": "Point", "coordinates": [ 103.807800, 1.326146 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "BOTANIC GARDENS MRT STATION", "EXIT_CODE": "B" }, "geometry": { "type": "Point", "coordinates": [ 103.815914, 1.322684 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "STEVENS MRT STATION", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.825678, 1.320350 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "NEWTON MRT STATION", "EXIT_CODE": "C" }, "geometry": { "type": "Point", "coordinates": [ 103.838242, 1.313617 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "LITTLE INDIA MRT STATION", "EXIT_CODE": "F" }, "geometry": { "type": "Point", "coordinates": [ 103.848304, 1.307683 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "ROCHOR MRT STATION", "EXIT_CODE": "B" }, "geometry": { "type": "Point", "coordinates": [ 103.853104, 1.304214 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "DOWNTOWN MRT STATION", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.852646, 1.279773 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "DOWNTOWN MRT STATION", "EXIT_CODE": "E" }, "geometry": { "type": "Point", "coordinates": [ 103.852478, 1.279527 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "DOWNTOWN MRT STATION", "EXIT_CODE": "B" }, "geometry": { "type": "Point", "coordinates": [ 103.852908, 1.279601 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "DOWNTOWN MRT STATION", "EXIT_CODE": "C" }, "geometry": { "type": "Point", "coordinates": [ 103.853152, 1.279444 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "DOWNTOWN MRT STATION", "EXIT_CODE": "D" }, "geometry": { "type": "Point", "coordinates": [ 103.853013, 1.279176 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "TELOK AYER MRT STATION", "EXIT_CODE": "C" }, "geometry": { "type": "Point", "coordinates": [ 103.848841, 1.282250 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "TELOK AYER MRT STATION", "EXIT_CODE": "B" }, "geometry": { "type": "Point", "coordinates": [ 103.848773, 1.282497 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "ONE-NORTH MRT STATION", "EXIT_CODE": "D" }, "geometry": { "type": "Point", "coordinates": [ 103.787784, 1.300074 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "KENT RIDGE MRT STATION", "EXIT_CODE": "C" }, "geometry": { "type": "Point", "coordinates": [ 103.784490, 1.293984 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "KENT RIDGE MRT STATION", "EXIT_CODE": "D" }, "geometry": { "type": "Point", "coordinates": [ 103.784534, 1.293218 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "LITTLE INDIA MRT STATION", "EXIT_CODE": "D" }, "geometry": { "type": "Point", "coordinates": [ 103.848999, 1.306854 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "BUKIT PANJANG MRT STATION", "EXIT_CODE": "A2" }, "geometry": { "type": "Point", "coordinates": [ 103.762034, 1.378766 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "Bright Hill", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.833333, 1.363414 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "Upper Thomson", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.832235, 1.354656 ] } },
{ "type": "Feature", "properties": { "STATION_NA": "Upper Thomson", "EXIT_CODE": "A" }, "geometry": { "type": "Point", "coordinates": [ 103.832393, 1.354548 ] } }
]
}
